# Generated by Django 5.1.4 on 2025-01-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(upload_to='movie_images'),
        ),
    ]
